---

- name: Check VM state
  ansible.builtin.shell:
    cmd: |
      VBoxManage showvminfo {{ packer_image }} --machinereadable | \
      awk -F= '$1=="VMState" {print $2}' | sed "s/\"//g"
  become: false
  register: vm_info
  changed_when: false

- name: Shutdown VM
  when: not packer_vm_destroy | bool
  block:

    - name: Shutdown VM
      ansible.builtin.command:
        cmd: VBoxManage controlvm {{ packer_image }} acpipowerbutton
      become: false
      register: vbox_shutdown
      when: vm_info.stdout != 'poweroff' and vm_info.stdout != ''

    - name: Wait for shutdown
      ansible.builtin.pause:
        seconds: 10
      when: vm_info.stdout != 'poweroff' and vm_info.stdout != ''

- name: Delete VM
  when: packer_vm_destroy | bool
  block:

    - name: Shutdown VM
      ansible.builtin.command:
        cmd: VBoxManage controlvm {{ packer_image }} poweroff
      become: false
      failed_when: false

    - name: Delete VM
      ansible.builtin.command:
        cmd: VBoxManage unregistervm ubuntu2404 --delete
      become: false
      failed_when: false

    - name: Delete existing build directory
      ansible.builtin.file:
        path: "{{ packer_build_path }}"
        state: absent

- name: Create build location
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
  loop:
    - "{{ packer_build_path }}"
    - "{{ packer_build_path }}/vm"

- name: Buildhost if localhost
  when: inventory_hostname == 'localhost'
  block:

    - name: Create packer config in YAML
      ansible.builtin.template:
        src: "{{ packer_template }}"
        dest: "{{ packer_build_path }}/{{ packer_image }}.yml"
        block_start_string: "<%"
        block_end_string: "%>"
        variable_start_string: "<="
        variable_end_string: "=>"
        mode: "0644"

    - name: Convert packer config to JSON
      ansible.builtin.copy:
        content: "{{ lookup('file', packer_build_path + '/' + packer_image + '.yml') | from_yaml | to_nice_json }}"
        dest: "{{ packer_build_path }}/{{ packer_image }}.json"
        mode: "0644"

- name: Buildhost if localhost
  when: inventory_hostname != 'localhost'
  block:

    - name: Create packer config in YAML
      ansible.builtin.template:
        src: "{{ packer_template }}"
        dest: "/tmp/{{ packer_image }}.yml"
        block_start_string: "<%"
        block_end_string: "%>"
        variable_start_string: "<="
        variable_end_string: "=>"
        mode: "0644"
      delegate_to: localhost

    - name: Convert packer config to JSON
      ansible.builtin.copy:
        content: "{{ lookup('file', '/tmp/' + packer_image + '.yml') | from_yaml | to_nice_json }}"
        dest: "/tmp/{{ packer_image }}.json"
        mode: "0644"
      delegate_to: localhost

    - name: Copy package files to buildhost
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ packer_build_path }}/{{ item | basename }}"
        mode: "0644"
      loop:
        - /tmp/{{ packer_image }}.yml
        - /tmp/{{ packer_image }}.json

- name: Copy extra files (RHEL)
  when: packer_image is search('rhel')
  block:

    - name: Copy kickstart file
      ansible.builtin.copy:
        src: /tmp/ks-{{ packer_image }}.cfg
        dest: "{{ packer_build_path }}/ks.cfg"
        mode: "0644"

- name: Copy extra files (Ubuntu)
  when: packer_image is search('ubuntu')
  block:
    - name: Copy user-data
      ansible.builtin.copy:
        src: /tmp/user-data.{{ packer_image }}
        dest: "{{ packer_build_path }}/user-data"
        mode: "0644"

    - name: Create empty meta-data file (Ubuntu)
      ansible.builtin.file:
        path: "{{ packer_build_path }}/meta-data"
        state: touch
        mode: "0644"

- name: Copy ansible code
  ansible.builtin.copy:
    src: "files/{{ packer_image }}/"
    dest: "{{ packer_build_path }}"

- name: Test if collection requirements exist
  ansible.builtin.stat:
    path: "{{ packer_build_path }}/ansible/collections/requirements.yml"
  register: __collections_requirements

- name: Install ansible collections
  community.general.ansible_galaxy_install:
    type: collection
    requirements_file: "{{ packer_build_path }}/ansible/collections/requirements.yml"
    executable: "{{ packer_ansible_venv | default(omit) }}"
    force: true
  when: __collections_requirements.stat.exists

- name: Test if roles requirements exist
  ansible.builtin.stat:
    path: "{{ packer_build_path }}/ansible/roles/requirements.yml"
  register: __roles_requirements

- name: Install ansible roles
  community.general.ansible_galaxy_install:
    type: role
    requirements_file: "{{ packer_build_path }}/ansible/roles/requirements.yml"
    dest: "{{ packer_build_path }}/ansible/roles/"
    executable: "{{ packer_ansible_venv | default(omit) }}"
    force: true
  when: __roles_requirements.stat.exists

- name: Execute packer
  ansible.builtin.shell:
    cmd: |
      set -e
      export VBOX_USER_HOME="{{ packer_build_path }}/vm"
      packer_config="{{ packer_image }}.json"
      packer_log="{{ packer_image }}.log"
      packer_venv="{{ packer_ansible_venv | default('') }}"
      [[ -n $packer_venv ]] && source $packer_venv/bin/activate
      # PACKER_LOG=1 packer build -on-error=abort $packer_config 2>&1 | tee $packer_log
      packer build -on-error=abort $packer_config 2>&1 | tee $packer_log
  args:
    chdir: "{{ packer_build_path }}"
    executable: /bin/bash
  changed_when: true
  register: __packer

- name: Retrieve logs
  ansible.builtin.command:
    cmd: cat {{ packer_build_path }}/{{ packer_image }}.log
    chdir: "{{ packer_build_path }}"
  changed_when: false
  register: __build

- name: Display logs
  ansible.builtin.debug:
    msg: "{{ __build.stdout_lines }}"

- name: See detailed logging on the build server
  ansible.builtin.debug:
    msg:
      host: "{{ packer_buildhost }}"
      path: "{{ packer_build_path }}"

- name: In case of failure, introduce pause of 4 hours
  ansible.builtin.pause:
    minutes: 240
  when: __packer.rc > 0 and packer_debug | default(false) | bool

- name: Stop processing
  ansible.builtin.fail:
    msg: Stopping image creation
  when: __packer.rc > 0
