---

- name: Get list of installed plugins
  ansible.builtin.command:
    cmd: packer plugins installed
  changed_when: false
  register: __packager_plugins_installed

- name: Install packer plugins
  ansible.builtin.command:
    cmd: packer plugins install {{ item }}
  register: __packer_plugin
  changed_when: true
  when: __packager_plugins_installed.stdout is not search(item)
  loop: "{{ packer_plugins }}"
